const { createCanvas } = require('canvas');

async function generateInvoice(data) {
    try {
        const width = 450;
        const height = 550;
        const canvas = createCanvas(width, height);
        const ctx = canvas.getContext('2d');

        // 1. Background Kertas Struk
        ctx.fillStyle = '#FFFFFF';
        ctx.fillRect(0, 0, width, height);

        // 2. Header Strip (Aksen Biru Harps)
        ctx.fillStyle = '#3498DB';
        ctx.fillRect(0, 0, width, 15);

        // 3. Nama Toko & Judul
        ctx.fillStyle = '#2C3E50';
        ctx.font = 'bold 28px Arial';
        ctx.textAlign = 'center';
        ctx.fillText('HARPS DIGITAL STORE', width / 2, 60);

        ctx.font = 'bold 16px Arial';
        ctx.fillStyle = '#7F8C8D';
        ctx.fillText('OFFICIAL E-RECEIPT', width / 2, 85);

        // 4. Garis Pembatas Atas
        ctx.strokeStyle = '#ECF0F1';
        ctx.lineWidth = 3;
        ctx.beginPath();
        ctx.moveTo(40, 110);
        ctx.lineTo(width - 40, 110);
        ctx.stroke();

        // 5. Rincian Transaksi
        ctx.textAlign = 'left';
        ctx.font = '16px Arial';
        ctx.fillStyle = '#34495E';
        let startY = 150;
        let lineH = 40;

        ctx.fillText('No. Invoice', 40, startY);
        ctx.fillText('Tanggal', 40, startY + lineH);
        ctx.fillText('Produk', 40, startY + lineH * 2);
        ctx.fillText('Metode', 40, startY + lineH * 3);
        ctx.fillText('Status', 40, startY + lineH * 4);

        // Data Dinamis dari Parameter
        ctx.textAlign = 'right';
        ctx.font = 'bold 16px Arial';
        ctx.fillStyle = '#2C3E50';
        ctx.fillText(data.invoice, width - 40, startY);
        ctx.fillText(data.date, width - 40, startY + lineH);
        
        // Potong nama produk kalau kepanjangan
        let shortProduct = data.product.length > 20 ? data.product.substring(0, 20) + '...' : data.product;
        ctx.fillText(shortProduct, width - 40, startY + lineH * 2);
        
        ctx.fillText('QRIS (Bayar.gg)', width - 40, startY + lineH * 3);

        // 6. Badge LUNAS
        ctx.fillStyle = '#2ECC71'; // Warna Hijau Success
        ctx.fillText('PAID / LUNAS ✅', width - 40, startY + lineH * 4);

        // 7. Garis Pembatas Bawah
        ctx.beginPath();
        ctx.moveTo(40, startY + lineH * 5);
        ctx.lineTo(width - 40, startY + lineH * 5);
        ctx.strokeStyle = '#ECF0F1';
        ctx.stroke();

        // 8. Total Harga
        ctx.textAlign = 'left';
        ctx.fillStyle = '#2C3E50';
        ctx.font = 'bold 22px Arial';
        ctx.fillText('TOTAL BAYAR', 40, startY + lineH * 6.5);

        ctx.textAlign = 'right';
        ctx.fillStyle = '#E74C3C'; // Warna Merah untuk Harga
        let hargaText = data.amount === 0 ? "GRATIS" : `Rp ${data.amount.toLocaleString('id-ID')}`;
        ctx.fillText(hargaText, width - 40, startY + lineH * 6.5);

        // 9. Footer
        ctx.textAlign = 'center';
        ctx.font = 'italic 14px Arial';
        ctx.fillStyle = '#95A5A6';
        ctx.fillText('Terima kasih telah berbelanja di Harps!', width / 2, height - 50);
        ctx.font = '12px Arial';
        ctx.fillText('Generated by Harps Auto-Payment System', width / 2, height - 25);

        return canvas.toBuffer('image/png');
    } catch (e) {
        console.error("Gagal cetak invoice:", e);
        return null;
    }
}

module.exports = { generateInvoice };
